BookManager.Web/Controllers/Categories/CategoriesController.cs
using BookManager.Domain.Core.IConfig;
using BookManager.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookManager.Web.Controllers.Categories
{
    public class CategoriesController : Controller
    {
        private readonly IUnityOfWork _table;

        public CategoriesController(IUnityOfWork table) => _table = table;


        public async Task<IActionResult> Index()
        {
            var categories = await _table.Categories.FindAll();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {

                var newCategory = await _table.Categories.Add(category);
                await _table.CompleteAsync();

                if (!newCategory)
                {
                    TempData["error"] = "Failed to create category";
                }

                TempData["success"] = "Category created successfully";
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id ==null || id==0)
            {
                return BadRequest();
            }

            var category = await _table.Categories.Find((int)id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category)
        {

            if (ModelState.IsValid)
            {
              
                var isUpdated = await _table.Categories.Update(category);

                if (!isUpdated)
                {
                    ModelState.AddModelError("Failed", "Failed to update category");
                    return View(category);
                }
                await _table.CompleteAsync();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }

            var category = await _table.Categories.Find((int)id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Category category)
        {
            var findCategory = await _table.Categories.Find(category.Id);
            if (findCategory != null)
            {
                if (findCategory.Books?.Count > 0)
                {
                    TempData["error"] = "Delete failed. Book(s) have been assigned to the Category";
                }
                else
                {
                    var isDeleted = await _table.Categories.Remove(findCategory);
                    if (isDeleted)
                    {
                        await _table.CompleteAsync();
                    }
                    TempData[isDeleted ? "success" : "error"] = isDeleted ? "Category deleted successfully" : "Failed to delete category";
                }
                
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
    }
}

BookManager.Web/Views/Categories/Create.cshtml
@model BookManager.Domain.Models.Category;

@{
    ViewData["Title"] = "New Category";
}

<div class="container p-4">
    <div class="row pb-2">
        <form asp-action="Create" method="post" class="col-md-6 ms-auto me-auto border border-primary p-3">
            <h4>New Category</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger mb-2"></div>
            <div class="mb-2">
                <label asp-for="Name" class="col-form-label"></label>
                <input class="form-control" asp-for="Name" />
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>

            <button class="btn btn-sm btn-success" type="submit"><i class="bi bi-save-fill"></i>&nbsp;Save</button>
            <a asp-controller="Categories" asp-action="Index" class="btn btn-sm btn-light"><i class="bi bi-arrow-left-circle-fill"></i>&nbsp;Back to List</a>
        </form>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial"></partial>
}

BookManager.Web/Views/Categories/Delete.cshtml
@model BookManager.Domain.Models.Category;

@{
    ViewData["Title"] = "Delete Category";
}

<div class="container p-4">
    <div class="row pb-2">
        <form asp-action="Delete" method="post" onsubmit="return confirm('Do you really want to delete the record?');" class="col-md-6 ms-auto me-auto border border-primary p-3">
            <input type="hidden" asp-for="@Model.Id" />
            <h4>Delete Category</h4>
            <hr />
            <div class="mb-2">
                <label asp-for="Name" class="col-form-label"></label>
                <input class="form-control" asp-for="Name" disabled />
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>

            <button class="btn btn-sm btn-danger" type="submit"><i class="bi bi-trash"></i>&nbsp;Delete</button>
            <a asp-controller="Categories" asp-action="Index" class="btn btn-sm btn-light"><i class="bi bi-arrow-left-circle-fill"></i>&nbsp;Back to List</a>
        </form>
    </div>
</div>

@section Scripts
    {
    <partial name="_Alert" />
}

BookManager.Web/Views/Categories/Edit.cshtml
@model BookManager.Domain.Models.Category;

@{
    ViewData["Title"] = "Edit Category";
}

<div class="container p-4">
    <div class="row pb-2">
        <form asp-action="Edit" method="Post" class="col-md-6 ms-auto me-auto border border-primary p-3">
            <h4>Edit Category</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger mb-2"></div>
            <div class="mb-2">
                <label asp-for="Name" class="col-form-label"></label>
                <input class="form-control" asp-for="Name" />
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>

            <button class="btn btn-sm btn-success" type="submit"><i class="bi bi-save-fill"></i>&nbsp;Save</button>
            <a asp-controller="Categories" asp-action="Index" class="btn btn-sm btn-light"><i class="bi bi-arrow-left-circle-fill"></i>&nbsp;Back to List</a>
        </form>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial"></partial>
}

BookManager.Web/Views/Categories/Index.cshtml
@model IEnumerable<BookManager.Domain.Models.Category>;
@{
    ViewData["Title"] = "Categories List";
}

<div class="container p-4">
    <div class="row pb-2">
        <div class="col-md-10 ms-auto me-auto border border-primary p-3">
            <div class="d-flex justify-content-between">
                <h5>Category List</h5>
                <a asp-controller="Categories" asp-action="Create" class="btn btn-sm btn-primary"><i class="bi bi-plus-circle-fill"></i>&nbsp;New Category</a>
            </div>
            <hr />
            <table class="table table-sm table-striped table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Total Books</th>
                        <th width="20%"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var category in Model)
                    {
                        <tr>
                            <td>@category.Name</td>
                            <td>@category.Books?.Count</td>
                            <td>
                                <div class="w-100">
                                    <a asp-controller="Categories" asp-action="Edit" asp-route-id="@category.Id" class="btn btn-sm btn-info"><i class="bi bi-pencil-square"></i>&nbsp;Edit</a>
                                    <a asp-controller="Categories" asp-action="Delete" asp-route-id="@category.Id" class="btn btn-sm btn-danger"><i class="bi bi-trash"></i>&nbsp;Delete</a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>