BookManager.Web/Controllers/Authors/AuthorsController.cs
using BookManager.Domain.Core.IConfig;
using BookManager.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookManager.Web.Controllers.Authors
{
    public class AuthorsController : Controller
    {
        private readonly IUnityOfWork _table;
        public AuthorsController(IUnityOfWork table)
        {
            _table = table;
        }
        public async Task<IActionResult> Index()
        {
            var authors = await _table.Authors.FindAll();
            return View(authors);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Author author)
        {
            if (ModelState.IsValid)
            {

                var newAuthor = await _table.Authors.Add(author);
                await _table.CompleteAsync();

                if (!newAuthor)
                {
                    TempData["error"] = "Failed to create author";
                }

                TempData["success"] = "Author created successfully";
                return RedirectToAction(nameof(Index));
            }

            return View(author);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }

            var author = await _table.Authors.Find((int)id);

            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(Author author)
        {
            if (ModelState.IsValid)
            {
                var isUpdated = await _table.Authors.Update(author);

                if (isUpdated)
                {
                    await _table.CompleteAsync();
                    TempData["success"] = "Author updated successfully";
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("Failed", "Failed to update author");
                return View(author);
            }
            return View(author);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }

            var author = await _table.Authors.Find((int)id);

            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }

            var author = await _table.Authors.Find((int)id);

            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Author author)
        {
            var findAuthor = await _table.Authors.Find(author.Id);
            if (findAuthor != null)
            {
                if (findAuthor.Books?.Count > 0)
                {
                    TempData["error"] = "Delete failed. Book(s) have been assigned to the Author";
                }
                else
                {
                    var isDeleted = await _table.Authors.Remove(findAuthor);
                    if (isDeleted)
                    {
                        await _table.CompleteAsync();
                    }
                    TempData[isDeleted ? "success" : "error"] = isDeleted ? "Author deleted successfully" : "Failed to delete author";
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }
    }
}

BookManager.Web/Controllers/Books/BooksController.cs
using BookManager.Domain.Core.IConfig;
using BookManager.Domain.Models;
using BookManager.Web.ViewModels.Books;
using Microsoft.AspNetCore.Mvc;

namespace BookManager.Web.Controllers.Books
{
    public class BooksController : Controller
    {
        private readonly IUnityOfWork _table;
        public BooksController(IUnityOfWork table)
        {
            _table = table;
        }
        public async Task<IActionResult> Index()
        {
            var books = await _table.Books.FindAll();
            return View(books);
        }

        public async Task<IActionResult> Create()
        {
            var createVM = new CreateBookViewModel()
            {
                AuthorList = await PopulateAuthorList(),
                CategoryList = await PopulateCategoryList()
            };

            return View(createVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateBookViewModel model)
        {
            if (ModelState.IsValid)
            {

                var author = await _table.Authors.Find(model.AuthorId);
                var category = await _table.Categories.Find(model.CategoryId);

                if (author == null)
                {
                    ModelState.AddModelError("Failed", "Author not found");
                    return View(model);
                }

                if (category == null)
                {
                    ModelState.AddModelError("Failed", "Category not found");
                    return View(model);
                }

                var newBook = new Book();
                newBook.Author = author;
                newBook.Category = category;
                newBook.Title = model.Title;
                newBook.Description = model.Description;
                newBook.ToTalPage = model.TotalPage;
                newBook.PublishedDate = model.PublishedDate;

                var isCreated = await _table.Books.Add(newBook);

                if (isCreated)
                {
                    await _table.CompleteAsync();
                    TempData["success"] = "Book created successfully";
                }
                else
                {
                    TempData["error"] = "Failed to create book";
                }

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }

            var book = await _table.Books.Find((int)id);

            if (book == null)
            {
                return NotFound();
            }

            var editBook = new EditBookViewModel()
            {
                Id = book.Id,
                Title = book.Title,
                Description = book.Description,
                TotalPage = book.ToTalPage,
                PublishedDate = book.PublishedDate,
                CategoryId = book.Category.Id,
                CategoryList = await PopulateCategoryList(),
                AuthorId = book.Author.Id,
                AuthorList = await PopulateAuthorList(),
            };

            return View(editBook);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(EditBookViewModel model)
        {
            if (ModelState.IsValid)
            {
                var book = await _table.Books.Find(model.Id);

                if (book == null)
                {
                    return BadRequest();
                }

                var author = await _table.Authors.Find(model.AuthorId);
                var category = await _table.Categories.Find(model.CategoryId);

                if (author == null)
                {
                    ModelState.AddModelError("Failed", "Invalid author");
                    return View(model);
                }

                if (category == null)
                {
                    ModelState.AddModelError("Failed", "Invalid category");
                    return View(model);
                }

                book.Title = model.Title;
                book.Description = model.Description;
                book.Author = author;
                book.Category = category;
                book.ToTalPage = model.TotalPage;
                book.PublishedDate = model.PublishedDate;               

                var isUpdated = await _table.Books.Update(book);

                if (isUpdated)
                {
                    await _table.CompleteAsync();
                }

                TempData[isUpdated ? "success" : "error"] = isUpdated ? "Book updated successfully" : "Failed to update book";
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }

            var book = await _table.Books.Find((int)id);

            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }

            var book = await _table.Books.Find((int)id);

            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Book book)
        {
            var findBook = await _table.Books.Find(book.Id);
            if (findBook != null) 
            {
                var isDeleted = await _table.Books.Remove(findBook);
                if (isDeleted)
                {
                    await _table.CompleteAsync();
                }
                TempData[isDeleted ? "success" : "error"] = isDeleted ? "Book deleted successfully" : "Failed to delete book";
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        private async Task<IEnumerable<Author>> PopulateAuthorList()
        {
            return await _table.Authors.FindAll();
        }

        private async Task<IEnumerable<Category>> PopulateCategoryList()
        {
            return await _table.Categories.FindAll();
        }
    }
}

BookManager.Web/Controllers/Users/UsersController.cs
using BookManager.Domain.Core.IConfig;
using BookManager.Domain.Helper;
using BookManager.Domain.Models;
using BookManager.Web.ViewModels.Users;
using Microsoft.AspNetCore.Mvc;

namespace BookManager.Web.Controllers.Users
{
    public class UsersController : Controller
    {
        private readonly IUnityOfWork _uow;

        public UsersController(IUnityOfWork uow)
        {
            _uow = uow;
        }


        public async Task<IActionResult> Index()
        {
            var users = await _uow.Users.FindAll(u => !u.IsDeleted);
            return View(users);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(User user)
        {
            if (ModelState.IsValid)
            {
                var checkUser = (ICollection<User>)await _uow.Users.FindAll(u => u.UserName.ToLower() == user.UserName.ToLower());

                if (checkUser.Count > 0)
                {
                    ModelState.AddModelError("", "Username already exist");
                    return View(user);
                }

                var password = Common.HashPassword(string.Format("{0}@{1}", user.UserName, DateTime.Now.Year.ToString()));
                user.Password = password;
                var isCreated = await _uow.Users.Add(user);
                if (isCreated)
                {
                    await _uow.CompleteAsync();
                }
                TempData[isCreated ? "success" : "error"] = isCreated ? "User created successfully" : "Failed to create user";
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }
            var user = await _uow.Users.Find((int)id);
            if (user == null)
            {
                return NotFound();
            }

            var editUser = new EditUserViewModel()
            {
                Id = user.Id,
                Name = user.Name,
                UserName = user.UserName,
                Status = user.Status,
            };
            return View(editUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {

            var user = await _uow.Users.Find(model.Id);
            if (user == null)
            {
                ModelState.AddModelError("", "Failed to update user");
                return View(model);
            }

            var checkUser = (ICollection<User>)await _uow.Users.FindAll(u => u.UserName.ToLower() == model.UserName.ToLower() && u.Id != model.Id);
            if (checkUser.Count > 0)
            {
                ModelState.AddModelError("", "Username already exist");
                return View(model);
            }

            user.Name = model.Name; 
            user.UserName = model.UserName;
            user.Role = model.Role;
            user.Status = model.Status;
            
            var isUpdated = await _uow.Users.Update(user);

            if (isUpdated)
            {
                await _uow.CompleteAsync();
                TempData["success"] = "User updated successfully";
                return RedirectToAction(nameof(Index));
            }

            ModelState.AddModelError("", "Failed to update user");
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return BadRequest();
            }
            var user = await _uow.Users.Find((int)id);
            if (user == null)
            {
                return NotFound();
            }

            var deleteUser = new EditUserViewModel()
            {
                Id = user.Id,
                Name = user.Name,
                UserName = user.UserName,
                Status = user.Status,
            };
            return View(deleteUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(EditUserViewModel model)
        {

            var user = await _uow.Users.Find(model.Id);
            if (user == null)
            {
                ModelState.AddModelError("", "Failed to delete user");
                return View(model);
            }

            user.Status = false;
            user.IsDeleted = true;

            var isDeleted = await _uow.Users.Update(user);

            if (isDeleted)
            {
                await _uow.CompleteAsync();
                TempData["success"] = "User deleted successfully";
                return RedirectToAction(nameof(Index));
            }

            ModelState.AddModelError("", "Failed to delete user");
            return View(model);
        }
    }
}

BookManager.Web/Views/Shared/_Alert.cshtml
<script type="text/javascript">
    //console.log("Hello");
</script>

BookManager.Web/Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Book Manager</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" asp-append-version="true">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Book Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                    </ul>
                    <div class="d-flex me-5">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted py-3 position-absolute bottom-0 w-100">
        <div class="container">
            &copy; <script>
                       document.write(new Date().getFullYear());
            </script> - Book Manager
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Book Manager</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" asp-append-version="true">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Books" asp-action="Index">Book Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Authors" asp-action="Index">
                                Authors
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                    </ul>
                    <div class="d-flex me-5">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Welcome, Guest</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#">My Profile</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Logout</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted py-3 position-absolute bottom-0 w-100">
        <div class="container">
            &copy; <script>
                       document.write(new Date().getFullYear());
            </script> - Book Manager
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookManager.Web/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]', "Success", {"timeOut": "3000" });
    </script>
}


@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]', "Oopss", { "timeOut": "3000" });
    </script>
}